### ISSUE TITLE
Second Screen failed to initate after upgrade to version 1.0.0

### ISSUE THREAD

**Issue by yadimr77** [VNAPNIC/presentation-displays#53]
My second screen devices (Imin) is working fine in 0.2.3 but after i try to upgrade to 1.0.0(newest) the second screen just returned white screen, 
the second screen seems failed to initiate it self.

**To Reproduce**
1. Working apps with second screen (eg: Imin) with presentation 0.2.3
2. upgrade the flutter_presentation to 1.0.0
3. the second screent won't initiate

has anayone facing the same issue? and how you guys fix it? 

thanks guys.

**Comment by MUSA-19542** [comment]
I have solved & Added Custom Methods
Go & check
https://github.com/MUSA-19542/FlutterCustom/tree/main

**Comment by SHEBINKUNIYIL** [comment]
add in pubspec.yaml


 ```yaml
  presentation_displays: 
    git:
      url: https://github.com/SHEBINKUNIYIL/presentation-displays.git
      ref: master
```

**Comment by yadimr77** [comment]
> add in pubspec.yaml
> 
> ```yaml
>  presentation_displays: 
>    git:
>      url: https://github.com/SHEBINKUNIYIL/presentation-displays.git
>      ref: master
> ```

did you got problem after upgrading to agp 8.5?

**Comment by fuadreza** [comment]
The problem is the update 1.0.0 introduce a new method and making it a breaking changes(It should noted as breaking changes).
Here's the commit that break the old version: [ea41be1](https://github.com/VNAPNIC/presentation-displays/commit/ea41be1332e4d587f82a5e967567b3d940200b52).
I am also not aware of this update when update the package. Here's the line that breaks things from `createFlutterEngine` method. 
```java
      FlutterInjector.instance().flutterLoader().startInitialization(context!!)Add commentMore actions
      val path = FlutterInjector.instance().flutterLoader().findAppBundlePath()
      val entrypoint = DartExecutor.DartEntrypoint(path, "secondaryDisplayMain")
      flutterEngine.dartExecutor.executeDartEntrypoint(entrypoint)
```
When you're not using the new methods to show the second display, you will get blank. The new method is:
```dart
@pragma('vm:entry-point')
void secondaryDisplayMain() {
  debugPrint('second main');
  runApp(const MySecondApp());
}
```
My approach is to revert the line in the `createFlutterEngine` method and It will be working again.
or you can just use mine here:
```yaml
  presentation_displays:
    git:
      url: https://github.com/fuadreza/presentation-displays
      ref: feat/1.0.2
```
